### ISSUE TITLE
How to buid app?

### ISSUE THREAD

**Issue by toanmh** [xhan/jailbreak-app-with-root-permission#1]
Thank xhan about this code. But I don't know it how to work. Can you help me build it?

**Comment by xhan** [comment]
after you installed Xcode(with command-line tools installed) , and get THEOS installed, then switch to project folder and type make && make package && make install

**Comment by MuMuTian** [comment]
你好，你的demo  make package为啥报错：cp: _/DEBIAN/postinst: No such file or directory
Can't open _/DEBIAN/postinst: No such file or directory.
chmod: _/DEBIAN/postinst: No such file or directory
make: *** [before-package] Error 1

**Comment by NotAlexNoyle** [comment]
My pull request fixes this, can anyone approve it?
